# replace foreign chars
replace_foreign_chars <- function(x)
{
  require(gsubfn);
  x <- gsub("s","s",x)
  x <- gsub("o","oe",x)
  x <- gsub("z","z",x)
  x <- gsub("?","ss",x)
  x <- gsub("?","y",x)
  x <- gsub("?","a",x)
  x <- gsub("?","a",x)
  x <- gsub("?","a",x)
  x <- gsub("?","a",x)
  x <- gsub("?","a",x)
  x <- gsub("?","a",x)
  x <- gsub("?","ae",x)
  x <- gsub("?","c",x)
  x <- gsub("?","e",x)
  x <- gsub("?","e",x)
  x <- gsub("?","e",x)
  x <- gsub("?","e",x)
  x <- gsub("?","i",x)
  x <- gsub("?","i",x)
  x <- gsub("?","i",x)
  x <- gsub("?","i",x)
  x <- gsub("?","d",x)
  x <- gsub("?","n",x)
  x <- gsub("?","o",x)
  x <- gsub("?","o",x)
  x <- gsub("?","o",x)
  x <- gsub("?","o",x)
  x <- gsub("?","o",x)
  x <- gsub("?","oe",x)
  x <- gsub("?","u",x)
  x <- gsub("?","u",x)
  x <- gsub("?","u",x)
  x <- gsub("?","u",x)
  x <- gsub("?","y",x)
  x <- gsub("?","y",x)
  x <- gsub("g","g",x)

  return(x)
}
